// Code generated by "go run cmd/bookmakers/generate_bookmakers.go"; DO NOT EDIT.

package bookmakers

import "github.com/jtyrus/the-odds-api-go/pkg/common/regions"

var (

    _1xBet_EU = Bookmaker { Region: regions.Europe, Key: "onexbet", Name: "1xBet"}

    _888sport_EU = Bookmaker { Region: regions.Europe, Key: "sport888", Name: "888sport"}

    _888sport_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "sport888", Name: "888sport"}

    Betclic_EU = Bookmaker { Region: regions.Europe, Key: "betclic", Name: "Betclic"}

    BetfairExchange_AU = Bookmaker { Region: regions.Australia, Key: "betfair_ex_au", Name: "Betfair Exchange"}

    BetfairExchange_EU = Bookmaker { Region: regions.Europe, Key: "betfair_ex_eu", Name: "Betfair Exchange"}

    BetfairExchange_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "betfair_ex_uk", Name: "Betfair Exchange"}

    BetfairSportsbook_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "betfair_sb_uk", Name: "Betfair Sportsbook"}

    BetMGM_US = Bookmaker { Region: regions.UnitedStates1, Key: "betmgm", Name: "BetMGM"}

    BetOnline_EU = Bookmaker { Region: regions.Europe, Key: "betonlineag", Name: "BetOnline.ag"}

    BetOnline_US = Bookmaker { Region: regions.UnitedStates1, Key: "betonlineag", Name: "BetOnline.ag"}

    betPARX_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "betparx", Name: "betPARX"}

    Betr_AU = Bookmaker { Region: regions.Australia, Key: "betr_au", Name: "Betr"}

    BetRivers_US = Bookmaker { Region: regions.UnitedStates1, Key: "betrivers", Name: "BetRivers"}

    Betsson_EU = Bookmaker { Region: regions.Europe, Key: "betsson", Name: "Betsson"}

    BetUS_US = Bookmaker { Region: regions.UnitedStates1, Key: "betus", Name: "BetUS"}

    BetVictor_EU = Bookmaker { Region: regions.Europe, Key: "betvictor", Name: "Bet Victor"}

    BetVictor_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "betvictor", Name: "Bet Victor"}

    Betway_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "betway", Name: "Betway"}

    BlueBet_AU = Bookmaker { Region: regions.Australia, Key: "bluebet", Name: "BlueBet"}

    Bovada_US = Bookmaker { Region: regions.UnitedStates1, Key: "bovada", Name: "Bovada"}

    BoyleSports_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "boylesports", Name: "BoyleSports"}

    Casumo_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "casumo", Name: "Casumo"}

    Coolbet_EU = Bookmaker { Region: regions.Europe, Key: "coolbet", Name: "Coolbet"}

    Coral_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "coral", Name: "Coral"}

    DraftKings_US = Bookmaker { Region: regions.UnitedStates1, Key: "draftkings", Name: "DraftKings"}

    ESPNBET_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "espnbet", Name: "ESPN BET"}

    Everygame_EU = Bookmaker { Region: regions.Europe, Key: "everygame", Name: "Everygame"}

    FanDuel_US = Bookmaker { Region: regions.UnitedStates1, Key: "fanduel", Name: "FanDuel"}

    Fliff_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "fliff", Name: "Fliff"}

    Grosvenor_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "grosvenor", Name: "Grosvenor"}

    HardRockBet_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "hardrockbet", Name: "Hard Rock Bet"}

    Ladbrokes_AU = Bookmaker { Region: regions.Australia, Key: "ladbrokes_au", Name: "Ladbrokes"}

    Ladbrokes_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "ladbrokes_uk", Name: "Ladbrokes"}

    LeoVegas_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "leovegas", Name: "LeoVegas"}

    Livescorebet_EU = Bookmaker { Region: regions.Europe, Key: "livescorebet_eu", Name: "Livescorebet (EU)"}

    LiveScoreBet_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "livescorebet", Name: "LiveScore Bet"}

    LowVig_US = Bookmaker { Region: regions.UnitedStates1, Key: "lowvig", Name: "LowVig.ag"}

    MarathonBet_EU = Bookmaker { Region: regions.Europe, Key: "marathonbet", Name: "Marathon Bet"}

    Matchbook_EU = Bookmaker { Region: regions.Europe, Key: "matchbook", Name: "Matchbook"}

    Matchbook_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "matchbook", Name: "Matchbook"}

    MrGreen_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "mrgreen", Name: "Mr Green"}

    MyBookie_EU = Bookmaker { Region: regions.Europe, Key: "mybookieag", Name: "MyBookie.ag"}

    MyBookie_US = Bookmaker { Region: regions.UnitedStates1, Key: "mybookieag", Name: "MyBookie.ag"}

    Neds_AU = Bookmaker { Region: regions.Australia, Key: "neds", Name: "Neds"}

    NordicBet_EU = Bookmaker { Region: regions.Europe, Key: "nordicbet", Name: "NordicBet"}

    PaddyPower_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "paddypower", Name: "Paddy Power"}

    Pinnacle_EU = Bookmaker { Region: regions.Europe, Key: "pinnacle", Name: "Pinnacle"}

    PlayUp_AU = Bookmaker { Region: regions.Australia, Key: "playup", Name: "PlayUp"}

    PointsBet_AU = Bookmaker { Region: regions.Australia, Key: "pointsbetau", Name: "PointsBet (AU)"}

    PointsBet_US = Bookmaker { Region: regions.UnitedStates1, Key: "pointsbetus", Name: "PointsBet (US)"}

    SISportsbook_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "sisportsbook", Name: "SI Sportsbook"}

    SkyBet_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "skybet", Name: "Sky Bet"}

    SportsBet_AU = Bookmaker { Region: regions.Australia, Key: "sportsbet", Name: "SportsBet"}

    SuperBook_US = Bookmaker { Region: regions.UnitedStates1, Key: "superbook", Name: "SuperBook"}

    Suprabets_EU = Bookmaker { Region: regions.Europe, Key: "suprabets", Name: "Suprabets"}

    TAB_AU = Bookmaker { Region: regions.Australia, Key: "tab", Name: "TAB"}

    Tipico_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "tipico_us", Name: "Tipico"}

    TopSport_AU = Bookmaker { Region: regions.Australia, Key: "topsport", Name: "TopSport"}

    Unibet_AU = Bookmaker { Region: regions.Australia, Key: "unibet", Name: "Unibet"}

    Unibet_EU = Bookmaker { Region: regions.Europe, Key: "unibet_eu", Name: "Unibet"}

    Unibet_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "unibet_uk", Name: "Unibet"}

    Unibet_US = Bookmaker { Region: regions.UnitedStates1, Key: "unibet_us", Name: "Unibet"}

    VirginBet_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "virginbet", Name: "Virgin Bet"}

    WilliamHill_EU = Bookmaker { Region: regions.Europe, Key: "williamhill", Name: "William Hill"}

    WilliamHill_UK = Bookmaker { Region: regions.UnitedKingdom, Key: "williamhill", Name: "William Hill (UK)"}

    WilliamHill_US = Bookmaker { Region: regions.UnitedStates1, Key: "williamhill_us", Name: "William Hill (Caesars)"}

    WindCreek_US2 = Bookmaker { Region: regions.UnitedStates2, Key: "windcreek", Name: "Wind Creek (Betfred PA)"}

    WynnBET_US = Bookmaker { Region: regions.UnitedStates1, Key: "wynnbet", Name: "WynnBET"}

)