// Code generated by "stringer --type Region"; DO NOT EDIT.

package regions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitedKingdom-0]
	_ = x[UnitedStates1-1]
	_ = x[UnitedStates2-2]
	_ = x[Europe-3]
	_ = x[Australia-4]
}

const _Region_name = "UnitedKingdomUnitedStates1UnitedStates2EuropeAustralia"

var _Region_index = [...]uint8{0, 13, 26, 39, 45, 54}

func (i Region) String() string {
	if i < 0 || i >= Region(len(_Region_index)-1) {
		return "Region(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
