// Code generated by "go run cmd/sports/generate_sports.go {apiKey}"; DO NOT EDIT.

package sports

var (

    _3LigaGermany = Sport { Key: "soccer_germany_liga3", Group: "Soccer", Title: "3. Liga - Germany", Description: "German Soccer",HasOutrights: false}

    ALeague = Sport { Key: "soccer_australia_aleague", Group: "Soccer", Title: "A-League", Description: "Aussie Soccer",HasOutrights: false}

    AFL = Sport { Key: "aussierules_afl", Group: "Aussie Rules", Title: "AFL", Description: "Aussie Football",HasOutrights: false}

    AfricaCupofNations = Sport { Key: "soccer_africa_cup_of_nations", Group: "Soccer", Title: "Africa Cup of Nations", Description: "Africa Cup of Nations",HasOutrights: false}

    AllsvenskanSweden = Sport { Key: "soccer_sweden_allsvenskan", Group: "Soccer", Title: "Allsvenskan - Sweden", Description: "Swedish Soccer",HasOutrights: false}

    AsiaCup = Sport { Key: "cricket_asia_cup", Group: "Cricket", Title: "Asia Cup", Description: "Asia Cup",HasOutrights: false}

    ATPAustralianOpen = Sport { Key: "tennis_atp_aus_open_singles", Group: "Tennis", Title: "ATP Australian Open", Description: "Men's Singles",HasOutrights: false}

    ATPFrenchOpen = Sport { Key: "tennis_atp_french_open", Group: "Tennis", Title: "ATP French Open", Description: "Men's Singles",HasOutrights: false}

    ATPUSOpen = Sport { Key: "tennis_atp_us_open", Group: "Tennis", Title: "ATP US Open", Description: "Men's Singles",HasOutrights: false}

    ATPWimbledon = Sport { Key: "tennis_atp_wimbledon", Group: "Tennis", Title: "ATP Wimbledon", Description: "Men's Singles",HasOutrights: false}

    AustrianFootballBundesliga = Sport { Key: "soccer_austria_bundesliga", Group: "Soccer", Title: "Austrian Football Bundesliga", Description: "Austrian Soccer",HasOutrights: false}

    BasketballEuroleague = Sport { Key: "basketball_euroleague", Group: "Basketball", Title: "Basketball Euroleague", Description: "Basketball Euroleague",HasOutrights: false}

    BelgiumFirstDiv = Sport { Key: "soccer_belgium_first_div", Group: "Soccer", Title: "Belgium First Div", Description: "Belgian First Division A",HasOutrights: false}

    BigBash = Sport { Key: "cricket_big_bash", Group: "Cricket", Title: "Big Bash", Description: "Big Bash League",HasOutrights: false}

    Boxing = Sport { Key: "boxing_boxing", Group: "Boxing", Title: "Boxing", Description: "Boxing Bouts",HasOutrights: false}

    BrazilSérieA = Sport { Key: "soccer_brazil_campeonato", Group: "Soccer", Title: "Brazil Série A", Description: "Brasileirão Série A",HasOutrights: false}

    BrazilSérieB = Sport { Key: "soccer_brazil_serie_b", Group: "Soccer", Title: "Brazil Série B", Description: "Campeonato Brasileiro Série B",HasOutrights: false}

    BundesligaGermany = Sport { Key: "soccer_germany_bundesliga", Group: "Soccer", Title: "Bundesliga - Germany", Description: "German Soccer",HasOutrights: false}

    Bundesliga2Germany = Sport { Key: "soccer_germany_bundesliga2", Group: "Soccer", Title: "Bundesliga 2 - Germany", Description: "German Soccer",HasOutrights: false}

    CFL = Sport { Key: "americanfootball_cfl", Group: "American Football", Title: "CFL", Description: "Canadian Football League",HasOutrights: false}

    Championship = Sport { Key: "soccer_efl_champ", Group: "Soccer", Title: "Championship", Description: "EFL Championship",HasOutrights: false}

    CopaLibertadores = Sport { Key: "soccer_conmebol_copa_libertadores", Group: "Soccer", Title: "Copa Libertadores", Description: "CONMEBOL Copa Libertadores",HasOutrights: false}

    CPLT20 = Sport { Key: "cricket_caribbean_premier_league", Group: "Cricket", Title: "CPLT20", Description: "Caribbean Premier League",HasOutrights: false}

    DenmarkSuperliga = Sport { Key: "soccer_denmark_superliga", Group: "Soccer", Title: "Denmark Superliga", Description: "Danish Soccer",HasOutrights: false}

    DutchEredivisie = Sport { Key: "soccer_netherlands_eredivisie", Group: "Soccer", Title: "Dutch Eredivisie", Description: "Dutch Soccer",HasOutrights: false}

    EFLCup = Sport { Key: "soccer_england_efl_cup", Group: "Soccer", Title: "EFL Cup", Description: "League Cup",HasOutrights: false}

    EkstraklasaPoland = Sport { Key: "soccer_poland_ekstraklasa", Group: "Soccer", Title: "Ekstraklasa - Poland", Description: "Polish Soccer",HasOutrights: false}

    EliteserienNorway = Sport { Key: "soccer_norway_eliteserien", Group: "Soccer", Title: "Eliteserien - Norway", Description: "Norwegian Soccer",HasOutrights: false}

    EPL = Sport { Key: "soccer_epl", Group: "Soccer", Title: "EPL", Description: "English Premier League",HasOutrights: false}

    FACup = Sport { Key: "soccer_fa_cup", Group: "Soccer", Title: "FA Cup", Description: "Football Association Challenge Cup",HasOutrights: false}

    FIFAWomensWorldCup = Sport { Key: "soccer_fifa_world_cup_womens", Group: "Soccer", Title: "FIFA Women's World Cup", Description: "FIFA Women's World Cup",HasOutrights: false}

    FIFAWorldCup = Sport { Key: "soccer_fifa_world_cup", Group: "Soccer", Title: "FIFA World Cup", Description: "FIFA World Cup 2022",HasOutrights: false}

    FIFAWorldCupWinner = Sport { Key: "soccer_fifa_world_cup_winner", Group: "Soccer", Title: "FIFA World Cup Winner", Description: "FIFA World Cup Winner 2026",HasOutrights: true}

    HockeyAllsvenskan = Sport { Key: "icehockey_sweden_allsvenskan", Group: "Ice Hockey", Title: "HockeyAllsvenskan", Description: "Swedish Hockey Allsvenskan",HasOutrights: false}

    ICCWorldCup = Sport { Key: "cricket_icc_world_cup", Group: "Cricket", Title: "ICC World Cup", Description: "ICC World Cup",HasOutrights: false}

    InternationalTwenty20 = Sport { Key: "cricket_international_t20", Group: "Cricket", Title: "International Twenty20", Description: "International Twenty20",HasOutrights: false}

    IPL = Sport { Key: "cricket_ipl", Group: "Cricket", Title: "IPL", Description: "Indian Premier League",HasOutrights: false}

    JLeague = Sport { Key: "soccer_japan_j_league", Group: "Soccer", Title: "J League", Description: "Japan Soccer League",HasOutrights: false}

    KLeague1 = Sport { Key: "soccer_korea_kleague1", Group: "Soccer", Title: "K League 1", Description: "Korean Soccer",HasOutrights: false}

    LaLigaSpain = Sport { Key: "soccer_spain_la_liga", Group: "Soccer", Title: "La Liga - Spain", Description: "Spanish Soccer",HasOutrights: false}

    LaLiga2Spain = Sport { Key: "soccer_spain_segunda_division", Group: "Soccer", Title: "La Liga 2 - Spain", Description: "Spanish Soccer",HasOutrights: false}

    League1 = Sport { Key: "soccer_england_league1", Group: "Soccer", Title: "League 1", Description: "EFL League 1",HasOutrights: false}

    League2 = Sport { Key: "soccer_england_league2", Group: "Soccer", Title: "League 2", Description: "EFL League 2 ",HasOutrights: false}

    LeagueofIreland = Sport { Key: "soccer_league_of_ireland", Group: "Soccer", Title: "League of Ireland", Description: "Airtricity League Premier Division",HasOutrights: false}

    LigaMX = Sport { Key: "soccer_mexico_ligamx", Group: "Soccer", Title: "Liga MX", Description: "Mexican Soccer",HasOutrights: false}

    Ligue1France = Sport { Key: "soccer_france_ligue_one", Group: "Soccer", Title: "Ligue 1 - France", Description: "French Soccer",HasOutrights: false}

    Ligue2France = Sport { Key: "soccer_france_ligue_two", Group: "Soccer", Title: "Ligue 2 - France", Description: "French Soccer",HasOutrights: false}

    MastersTournamentWinner = Sport { Key: "golf_masters_tournament_winner", Group: "Golf", Title: "Masters Tournament Winner", Description: "2024 Winner",HasOutrights: true}

    MLB = Sport { Key: "baseball_mlb", Group: "Baseball", Title: "MLB", Description: "Major League Baseball",HasOutrights: false}

    MLBPreseason = Sport { Key: "baseball_mlb_preseason", Group: "Baseball", Title: "MLB Preseason", Description: "Major League Baseball",HasOutrights: false}

    MLBWorldSeriesWinner = Sport { Key: "baseball_mlb_world_series_winner", Group: "Baseball", Title: "MLB World Series Winner", Description: "World Series Winner 2023",HasOutrights: true}

    MLS = Sport { Key: "soccer_usa_mls", Group: "Soccer", Title: "MLS", Description: "Major League Soccer",HasOutrights: false}

    MMA = Sport { Key: "mma_mixed_martial_arts", Group: "Mixed Martial Arts", Title: "MMA", Description: "Mixed Martial Arts",HasOutrights: false}

    NBA = Sport { Key: "basketball_nba", Group: "Basketball", Title: "NBA", Description: "US Basketball",HasOutrights: false}

    NBAChampionshipWinner = Sport { Key: "basketball_nba_championship_winner", Group: "Basketball", Title: "NBA Championship Winner", Description: "Championship Winner 2023/2024",HasOutrights: true}

    NBAPreseason = Sport { Key: "basketball_nba_preseason", Group: "Basketball", Title: "NBA Preseason", Description: "US Basketball",HasOutrights: false}

    NCAABaseball = Sport { Key: "baseball_ncaa", Group: "Baseball", Title: "NCAA Baseball", Description: "US College Baseball",HasOutrights: false}

    NCAAB = Sport { Key: "basketball_ncaab", Group: "Basketball", Title: "NCAAB", Description: "US College Basketball",HasOutrights: false}

    NCAABChampionshipWinner = Sport { Key: "basketball_ncaab_championship_winner", Group: "Basketball", Title: "NCAAB Championship Winner", Description: "US College Basketball Championship Winner",HasOutrights: true}

    NCAAF = Sport { Key: "americanfootball_ncaaf", Group: "American Football", Title: "NCAAF", Description: "US College Football",HasOutrights: false}

    NCAAFChampionshipWinner = Sport { Key: "americanfootball_ncaaf_championship_winner", Group: "American Football", Title: "NCAAF Championship Winner", Description: "US College Football Championship Winner",HasOutrights: true}

    NFL = Sport { Key: "americanfootball_nfl", Group: "American Football", Title: "NFL", Description: "US Football",HasOutrights: false}

    NFLPreseason = Sport { Key: "americanfootball_nfl_preseason", Group: "American Football", Title: "NFL Preseason", Description: "US Football",HasOutrights: false}

    NFLSuperBowlWinner = Sport { Key: "americanfootball_nfl_super_bowl_winner", Group: "American Football", Title: "NFL Super Bowl Winner", Description: "Super Bowl Winner 2023/2024",HasOutrights: true}

    NHL = Sport { Key: "icehockey_nhl", Group: "Ice Hockey", Title: "NHL", Description: "US Ice Hockey",HasOutrights: false}

    NHLChampionshipWinner = Sport { Key: "icehockey_nhl_championship_winner", Group: "Ice Hockey", Title: "NHL Championship Winner", Description: "Stanley Cup Winner 2022/2023",HasOutrights: true}

    NRL = Sport { Key: "rugbyleague_nrl", Group: "Rugby League", Title: "NRL", Description: "Aussie Rugby League",HasOutrights: false}

    OneDayInternationals = Sport { Key: "cricket_odi", Group: "Cricket", Title: "One Day Internationals", Description: "One Day Internationals",HasOutrights: false}

    PakistanSuperLeague = Sport { Key: "cricket_psl", Group: "Cricket", Title: "Pakistan Super League", Description: "Pakistan Super League",HasOutrights: false}

    PGAChampionshipWinner = Sport { Key: "golf_pga_championship_winner", Group: "Golf", Title: "PGA Championship Winner", Description: "2024 Winner",HasOutrights: true}

    PremiershipScotland = Sport { Key: "soccer_spl", Group: "Soccer", Title: "Premiership - Scotland", Description: "Scottish Premiership",HasOutrights: false}

    PrimeiraLigaPortugal = Sport { Key: "soccer_portugal_primeira_liga", Group: "Soccer", Title: "Primeira Liga - Portugal", Description: "Portugese Soccer",HasOutrights: false}

    PrimeraDivisiónArgentina = Sport { Key: "soccer_argentina_primera_division", Group: "Soccer", Title: "Primera División - Argentina", Description: "Argentine Primera División",HasOutrights: false}

    PrimeraDivisiónChile = Sport { Key: "soccer_chile_campeonato", Group: "Soccer", Title: "Primera División - Chile", Description: "Campeonato Chileno",HasOutrights: false}

    SerieAItaly = Sport { Key: "soccer_italy_serie_a", Group: "Soccer", Title: "Serie A - Italy", Description: "Italian Soccer",HasOutrights: false}

    SerieBItaly = Sport { Key: "soccer_italy_serie_b", Group: "Soccer", Title: "Serie B - Italy", Description: "Italian Soccer",HasOutrights: false}

    SHL = Sport { Key: "icehockey_sweden_hockey_league", Group: "Ice Hockey", Title: "SHL", Description: "Swedish Hockey League",HasOutrights: false}

    SuperLeagueChina = Sport { Key: "soccer_china_superleague", Group: "Soccer", Title: "Super League - China", Description: "Chinese Soccer",HasOutrights: false}

    SuperLeagueGreece = Sport { Key: "soccer_greece_super_league", Group: "Soccer", Title: "Super League - Greece", Description: "Greek Soccer",HasOutrights: false}

    SuperettanSweden = Sport { Key: "soccer_sweden_superettan", Group: "Soccer", Title: "Superettan - Sweden", Description: "Swedish Soccer",HasOutrights: false}

    SwissSuperleague = Sport { Key: "soccer_switzerland_superleague", Group: "Soccer", Title: "Swiss Superleague", Description: "Swiss Soccer",HasOutrights: false}

    T20Blast = Sport { Key: "cricket_t20_blast", Group: "Cricket", Title: "T20 Blast", Description: "T20 Blast",HasOutrights: false}

    TestMatches = Sport { Key: "cricket_test_match", Group: "Cricket", Title: "Test Matches", Description: "International Test Matches",HasOutrights: false}

    TheHundred = Sport { Key: "cricket_the_hundred", Group: "Cricket", Title: "The Hundred", Description: "The Hundred",HasOutrights: false}

    TheOpenWinner = Sport { Key: "golf_the_open_championship_winner", Group: "Golf", Title: "The Open Winner", Description: "2024 Winner",HasOutrights: true}

    TurkeySuperLeague = Sport { Key: "soccer_turkey_super_league", Group: "Soccer", Title: "Turkey Super League", Description: "Turkish Soccer",HasOutrights: false}

    UEFAChampionsLeague = Sport { Key: "soccer_uefa_champs_league", Group: "Soccer", Title: "UEFA Champions League", Description: "European Champions League",HasOutrights: false}

    UEFAChampionsLeagueQualification = Sport { Key: "soccer_uefa_champs_league_qualification", Group: "Soccer", Title: "UEFA Champions League Qualification", Description: "European Champions League Qualification",HasOutrights: false}

    UEFAEuroQualification = Sport { Key: "soccer_uefa_euro_qualification", Group: "Soccer", Title: "UEFA Euro Qualification", Description: "European Championship Qualification",HasOutrights: false}

    UEFAEuropaConferenceLeague = Sport { Key: "soccer_uefa_europa_conference_league", Group: "Soccer", Title: "UEFA Europa Conference League", Description: "UEFA Europa Conference League",HasOutrights: false}

    UEFAEuropaLeague = Sport { Key: "soccer_uefa_europa_league", Group: "Soccer", Title: "UEFA Europa League", Description: "European Europa League",HasOutrights: false}

    UEFANationsLeague = Sport { Key: "soccer_uefa_nations_league", Group: "Soccer", Title: "UEFA Nations League", Description: "UEFA Nations League",HasOutrights: false}

    USOpenWinner = Sport { Key: "golf_us_open_winner", Group: "Golf", Title: "US Open Winner", Description: "2024 Winner",HasOutrights: true}

    USPresidentialElectionsWinner = Sport { Key: "politics_us_presidential_election_winner", Group: "Politics", Title: "US Presidential Elections Winner", Description: "2024 US Presidential Election Winner",HasOutrights: true}

    VeikkausliigaFinland = Sport { Key: "soccer_finland_veikkausliiga", Group: "Soccer", Title: "Veikkausliiga - Finland", Description: "Finnish  Soccer",HasOutrights: false}

    WNBA = Sport { Key: "basketball_wnba", Group: "Basketball", Title: "WNBA", Description: "US Basketball",HasOutrights: false}

    WorldCup = Sport { Key: "rugbyunion_world_cup", Group: "Rugby Union", Title: "World Cup", Description: "World Cup 2023",HasOutrights: false}

    WTAAustralianOpen = Sport { Key: "tennis_wta_aus_open_singles", Group: "Tennis", Title: "WTA Australian Open", Description: "Women's Singles",HasOutrights: false}

    WTAFrenchOpen = Sport { Key: "tennis_wta_french_open", Group: "Tennis", Title: "WTA French Open", Description: "Women's Singles",HasOutrights: false}

    WTAUSOpen = Sport { Key: "tennis_wta_us_open", Group: "Tennis", Title: "WTA US Open", Description: "Women's Singles",HasOutrights: false}

    WTAWimbledon = Sport { Key: "tennis_wta_wimbledon", Group: "Tennis", Title: "WTA Wimbledon", Description: "Women's Singles",HasOutrights: false}

)